config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :children

  root 'children#index'

end

app/models/child.rb
class Child < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: [:show, :edit, :update, :destroy]

  # GET /children
  # GET /children.json
  def index        
    @children = Child.all
  end

  # GET /children/1
  # GET /children/1.json
  def show
  end

  # GET /children/new
  def new
    @child = Child.new
  end

  # GET /children/1/edit
  def edit
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        format.html { redirect_to @child, notice: 'Child was successfully created.' }
        format.json { render :show, status: :created, location: @child }
      else
        format.html { render :new }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1
  # PATCH/PUT /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to @child, notice: 'Child was successfully updated.' }
        format.json { render :show, status: :ok, location: @child }
      else
        format.html { render :edit }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child.destroy
    respond_to do |format|
      format.html { redirect_to children_url, notice: 'Child was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def child_params
      params.require(:child).permit(:name, :birth_date, :gender, :language, :father_name, :father_phone, :mother_name, :mother_phone, :voter_id, :address, :dist_character, :disability_status, :photo, :finger_print, :issue_date, :issuer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/children/_form.html.erb
<%= form_for(@child) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br>
    <%= f.date_select :birth_date %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :father_name %><br>
    <%= f.text_field :father_name %>
  </div>
  <div class="field">
    <%= f.label :father_phone %><br>
    <%= f.number_field :father_phone %>
  </div>
  <div class="field">
    <%= f.label :mother_name %><br>
    <%= f.text_field :mother_name %>
  </div>
  <div class="field">
    <%= f.label :mother_phone %><br>
    <%= f.number_field :mother_phone %>
  </div>
  <div class="field">
    <%= f.label :voter_id %><br>
    <%= f.text_field :voter_id %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :dist_character %><br>
    <%= f.text_area :dist_character %>
  </div>
  <div class="field">
    <%= f.label :disability_status %><br>
    <%= f.text_area :disability_status %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :finger_print %><br>
    <%= f.text_field :finger_print %>
  </div>
  <div class="field">
    <%= f.label :issue_date %><br>
    <%= f.date_select :issue_date %>
  </div>
  <div class="field">
    <%= f.label :issuer %><br>
    <%= f.text_field :issuer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/children/edit.html.erb
<h1>Editing Child</h1>

<%= render 'form' %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Children <%=  %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birth date</th>
      <th>Gender</th>
      <th>Language</th>
      <th>Father name</th>
      <th>Father phone</th>
      <th>Mother name</th>
      <th>Mother phone</th>
      <th>Voter</th>
      <th>Address</th>
      <th>Dist character</th>
      <th>Disability status</th>
      <th>Photo</th>
      <th>Finger print</th>
      <th>Issue date</th>
      <th>Issuer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @children.each do |child| %>
      <tr>
        <td><%= child.name %></td>
        <td><%= child.birth_date %></td>
        <td><%= child.gender %></td>
        <td><%= child.language %></td>
        <td><%= child.father_name %></td>
        <td><%= child.father_phone %></td>
        <td><%= child.mother_name %></td>
        <td><%= child.mother_phone %></td>
        <td><%= child.voter_id %></td>
        <td><%= child.address %></td>
        <td><%= child.dist_character %></td>
        <td><%= child.disability_status %></td>
        <td><%= child.photo %></td>
        <td><%= child.finger_print %></td>
        <td><%= child.issue_date %></td>
        <td><%= child.issuer %></td>
        <td><%= link_to 'Show', child %></td>
        <td><%= link_to 'Edit', edit_child_path(child) %></td>
        <td><%= link_to 'Destroy', child, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Child', new_child_path %>

app/views/children/new.html.erb
<h1>Registration Form</h1>

<%= render 'form' %>

<%= link_to 'Back', children_path %>

app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @child.name %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @child.birth_date %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @child.gender %>
</p>

<p>
  <strong>Language:</strong>
  <%= @child.language %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @child.father_name %>
</p>

<p>
  <strong>Father phone:</strong>
  <%= @child.father_phone %>
</p>

<p>
  <strong>Mother name:</strong>
  <%= @child.mother_name %>
</p>

<p>
  <strong>Mother phone:</strong>
  <%= @child.mother_phone %>
</p>

<p>
  <strong>Voter:</strong>
  <%= @child.voter_id %>
</p>

<p>
  <strong>Address:</strong>
  <%= @child.address %>
</p>

<p>
  <strong>Dist character:</strong>
  <%= @child.dist_character %>
</p>

<p>
  <strong>Disability status:</strong>
  <%= @child.disability_status %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @child.photo %>
</p>

<p>
  <strong>Finger print:</strong>
  <%= @child.finger_print %>
</p>

<p>
  <strong>Issue date:</strong>
  <%= @child.issue_date %>
</p>

<p>
  <strong>Issuer:</strong>
  <%= @child.issuer %>
</p>

<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Findbulu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <p class="navbar-text pull-right">
	<% if user_signed_in? %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	<% end %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>